### ISSUE TITLE
Way to comment out all lines of an include?

### ISSUE THREAD

**Issue by eihli** [justinmeiners/srcweave#24]
I've got some code like below and I'd like to comment out all of the `64 bit test loop` with a single `//` line. But right now it only prefixes the first line of the inclusion.

```c
--- /pagecount32vs64.c
@{Includes, initializations, and external function declarations}
int main(int argc, char** argv) {
    @{Initializations32}
    @{Baseline32}

    @{32 bit test loop}
    // @{64 bit test loop}
    @{Results output}
}
---
```

I see how this behavior is useful because it lets you do things like:

```js
someArray.@{filter and map chain}
```

Where `filter and map chain` is something like:
```
--- filter and map chain
map(double)
.filter(even)
.reduce(add)
---
```

You don't want `someArray` to be prefixed to each line there, and `srcweave` doesn't know there's a difference between `//` and `someArray`. It doesn't know that one's a comment prefix and one's not.

So... I'm happy to work on the implementation. But what's the best way to go about this?

Maybe something like a "comment directive"? Something scoped project-wide? Or scoped per file? Or scoped per code-block?

Maybe something like

```
--- /pagecount32vs64.c --- comment: //
foo
// bar
baz
---
```

**Comment by eihli** [comment]
There are reasons to not make any changes related to this. 

If you're commenting stuff out as part of development and debugging then this problem is solved by other tools. Just make two commits in version control and jump back and forth. Or use your editor to undo/redo.

Within srcweave, instead of commenting out a block you can create an empty block and use that as the include.

I'm strongly leaning towards thinking this should not change.

**Comment by justinmeiners** [comment]
Thanks for writing this in detail. I would prefer as little of a relationship between the particular programming language and the srcweave tool, as ultimately it's a text manipulation system. Keeping it focused on text makes it's behavior predictable and easier to integrate with other unix tools.

With that said, here are two options I can think of:

1. Ensure that including an unknown block only produces a warning instead of an error. Then you could just add a character to the front of the identifier, and it would create a bogus include with no effect on the source code. This is similar to your idea of including an empty block, but you don't have to make an empty block.

2. Create a special form representing our own comments in the literate system. For example, perhaps `?{64 bit test loop}` could be ignored by the system.


I am leaning towards something like option 1. What are your thoughts?

**Comment by eihli** [comment]
> 1. Ensure that including an unknown block only produces a warning instead of an error. 

Yeah this sounds good and reasonable. Not erroring is closer to the behavior of at least one existing tool, Org-mode, which isn't even warning me when I export with a non-existent block.

```
#+begin_src shell :noweb yes
echo "hello"
<<goodbye>>
<<world>>
#+end_src

#+NAME: world
#+begin_src shell
echo "world"
#+end_src
```
